// user reducer
export const AUTH_START = "AUTH_START";
export const AUTH_GENERATE_TOKEN = "AUTH_GENERATE_TOKEN";
export const AUTH_LOGIN_CODE_SENT_SUCCESS = "AUTH_LOGIN_CODE_SENT_SUCCESS";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";


export const UPDATE_PROFILE_START = "UPDATE_PROFILE_START";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";


// uiState

export const ADD_MODAL = "ADD_MODAL"
export const DELETE_MODAL = "DELETE_MODAL"
export const UPDATE_VISIBILITY = "SHOW_MODAL"