version: '3'

services:

  frontend:
    container_name: react-dev
    build:
      context: react
    volumes:
      - ./react/src:/app/src
    ports:
      - 3001:3000

  backend:
    container_name: django-dev
    build:
      context: django
    command: python django/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8001:8000