version: '3'

services:
  frontend:
    container_name: react-dev
    build:
      context: .
      dockerfile: react/Dockerfile
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  backend:
    container_name: django-dev
    build:
      context: .
      dockerfile: django/Dockerfile
    command: python django/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/code
    ports:
    - 8001:8000