# Generated by Django 2.2.5 on 2019-12-12 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='sex',
        ),
    ]
