# Generated by Django 2.2.5 on 2019-12-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191213_1304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
