# Generated by Django 2.2.5 on 2019-12-15 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='api',
            new_name='category',
        ),
    ]
