# Generated by Django 2.2.5 on 2019-12-16 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191216_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='company_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
